#server:
#  port: 8099  # Spring boot Server port

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.7:3306/entertainment?serverTimezone=UTC&characterEncoding=UTF-8
    username: deogicorgi
    password: deogicorgi1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate :
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: create
#    generate-ddl: true
#        ddl-auto: create
#  test :
#    database :
#      replace : NONE
